name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: ''
          - platform: 'ubuntu-latest'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: |
          cd packages/shared && npm install
          cd ../renderer && npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'HippoMind v__VERSION__'
          releaseBody: |
            # HippoMind v__VERSION__

            Your privacy-first mind mapping app is ready to download!

            ## 📥 Download for your platform:

            - **macOS**: Download the `.dmg` file (Apple Silicon & Intel)
            - **Windows**: Download the `.exe` installer
            - **Linux**: Download the `.AppImage` file

            ## 🆕 What's new in this version

            - Initial release of HippoMind
            - 100% offline mind mapping
            - Beautiful themes (Light, Dark, Sepia, Slate)
            - Unlimited nodes and mind maps
            - Auto-save every 30 seconds
            - Full keyboard shortcuts support

            ## 🔑 Activation

            After installation, you'll need to enter your license key.

            Don't have a license yet? [Purchase HippoMind](https://hippomind.org)

            ## 📖 Documentation

            Need help? Visit [hippomind.org](https://hippomind.org) or contact support@hippomind.org
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
